# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=255, unique=True)),
                ('passport_number', models.CharField(max_length=255, unique=True)),
                ('passport_issuing_country', models.CharField(max_length=255)),
                ('passport_expiration_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('passenger_comments_update', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comments for Updating')),
                ('immigration_details', models.CharField(blank=True, max_length=255, null=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('trip_type', models.CharField(choices=[('one-way', 'One Way'), ('round-trip', 'Round Trip')], max_length=20)),
                ('allowed_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Allowed Maximum Weight')),
                ('max_check_bags', models.PositiveIntegerField(blank=True, null=True, verbose_name='Allowed Maximum Pieces')),
                ('checked_in_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Checked in Weight')),
                ('checked_in_bags', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Bags Checked in')),
                ('booking_comments', models.TextField(blank=True, null=True, verbose_name='Booking Comments')),
                ('booking_ticket_id', models.CharField(max_length=100, verbose_name='Ticket ID')),
                ('booking_reference', models.CharField(max_length=100, verbose_name='Booking Reference')),
                ('update_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Update Comments')),
                ('booking_status', models.CharField(choices=[('', '---------'), ('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Missed', 'Missed')], default='Active', max_length=20)),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_dispatch.flight')),
                ('multi_city_flights', models.ManyToManyField(related_name='multicity_flight', to='flight_dispatch.flight', verbose_name='Multi City Flights')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passenger', verbose_name='Passenger')),
                ('return_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_flight', to='flight_dispatch.flight')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120, unique=True, verbose_name='Group Name')),
                ('group_status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], default='Active', max_length=20, verbose_name='Group Status')),
                ('group_updating_comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('passengers_ids', models.ManyToManyField(blank=True, to='passengers.passenger', verbose_name='Passengers')),
            ],
        ),
    ]
