# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinCrewGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120, unique=True, verbose_name='Group Name')),
                ('group_status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], default='Active', max_length=20, verbose_name='Group Status')),
                ('group_updating_comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_cabin_crew_group', to=settings.AUTH_USER_MODEL)),
                ('crew_ids', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Passengers')),
            ],
        ),
    ]
