# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50, unique=True, verbose_name='Flight Number')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival Time')),
                ('return_departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Return Departure Time')),
                ('return_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name=' Return Arrival Time')),
                ('trip_type', models.CharField(choices=[('', '---------'), ('one-way', 'One Way'), ('round-trip', 'Round Trip')], default='one-way', max_length=20, verbose_name='Trip Type')),
                ('flight_status', models.CharField(choices=[('Dispatched', 'Dispatched'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled'), ('not-taken', 'Not Taken'), ('Dispatching', 'Dispatching'), ('OnTrip', 'OnTrip'), ('Delayed', 'Delayed'), ('Arrived', 'Arrived'), ('Completed', 'Completed')], default='Scheduled', max_length=30, verbose_name='Flight Status')),
                ('flight_dispatch_method', models.CharField(choices=[('', '---------'), ('Automated', 'Automated'), ('Manual', 'Manual')], default='Automated', max_length=30, verbose_name='Dispatch Method')),
                ('flight_leg_reference', models.CharField(max_length=100, verbose_name='Flight Booking Reference')),
                ('flight_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Flight Comments')),
                ('update_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Update Comments')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Recorded')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('tech_log', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
    ]
