# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_dispatch', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.aircraft', verbose_name='Aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='cabin_crew',
            field=models.ManyToManyField(blank=True, related_name='cabin_crew_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Cabin Crew'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_destination', to='maintenance.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_crew',
            field=models.ManyToManyField(blank=True, related_name='flight_crew_schedule', to=settings.AUTH_USER_MODEL, verbose_name='Flight Crew'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.airport'),
        ),
    ]
