# Generated by Django 5.1.6 on 2025-12-11 10:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftmaincomponent',
            options={'verbose_name': 'Aircraft Main Component', 'verbose_name_plural': 'Aircraft Main Components'},
        ),
        migrations.AlterModelOptions(
            name='aircraftsub2component',
            options={'verbose_name': 'Aircraft Sub2 Component', 'verbose_name_plural': 'Aircraft Sub2 Components'},
        ),
        migrations.AlterModelOptions(
            name='aircraftsub3component',
            options={'verbose_name': 'Aircraft Sub3 Component', 'verbose_name_plural': 'Aircraft Sub3 Components'},
        ),
        migrations.AlterModelOptions(
            name='aircraftsubcomponent',
            options={'verbose_name': 'Aircraft Sub Component', 'verbose_name_plural': 'Aircraft Sub Components'},
        ),
        migrations.CreateModel(
            name='ComponentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type_schedule', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance'), ('Re-Provisioned', 'Re-Provisioned')], max_length=100, verbose_name='Maintenance Type')),
                ('object_id', models.PositiveIntegerField()),
                ('maintenance_type', models.CharField(choices=[('Class_A', 'Class A'), ('Class_B', 'Class B'), ('Class_C', 'Class C'), ('Class_D', 'Class D')], max_length=100, verbose_name='Maintenance Type')),
                ('maintenance_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maintenance Hours')),
                ('maintenance_hours_added', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maintenance Hours Added')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('remarks', models.TextField(max_length=500, verbose_name='Maintenance Remarks')),
                ('maintenance_report', models.FileField(upload_to='', verbose_name='Maintenance Report')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('update_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Update Comments')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Component Maintenance',
                'verbose_name_plural': 'Component Maintenances',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='maintenance_content_80f1fc_idx'), models.Index(fields=['start_date'], name='maintenance_start_d_36d723_idx')],
            },
        ),
    ]
