# Generated by Django 6.0 on 2025-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_aircraftmaincomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftmaincomponent',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recommended Next Date'),
        ),
        migrations.AddField(
            model_name='aircraftmaintenance',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recommended Next Date'),
        ),
        migrations.AddField(
            model_name='aircraftsub2component',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recommended Next Date'),
        ),
        migrations.AddField(
            model_name='aircraftsub3component',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recommended Next Date'),
        ),
        migrations.AddField(
            model_name='aircraftsubcomponent',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recommended Next Date'),
        ),
    ]
