# Generated by Django 6.0 on 2025-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_aircraftmaincomponent_next_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmaincomponent',
            name='component_status',
            field=models.CharField(choices=[('Attached', 'Attached'), ('Detached', 'Detached'), ('Stores', 'Stores')], default='Attached', max_length=100, verbose_name='Component Status'),
        ),
        migrations.AlterField(
            model_name='aircraftsub2component',
            name='component_status',
            field=models.CharField(choices=[('Attached', 'Attached'), ('Detached', 'Detached'), ('Stores', 'Stores')], default='Attached', max_length=100, verbose_name='Component Status'),
        ),
        migrations.AlterField(
            model_name='aircraftsub3component',
            name='component_status',
            field=models.CharField(choices=[('Attached', 'Attached'), ('Detached', 'Detached'), ('Stores', 'Stores')], default='Attached', max_length=100, verbose_name='Component Status'),
        ),
        migrations.AlterField(
            model_name='aircraftsubcomponent',
            name='component_status',
            field=models.CharField(choices=[('Attached', 'Attached'), ('Detached', 'Detached'), ('Stores', 'Stores')], default='Attached', max_length=100, verbose_name='Component Status'),
        ),
    ]
