# Generated by Django 6.0 on 2025-12-13 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_aircraftmaincomponent_component_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='componentmaintenance',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual End Date'),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='actual_hours_added',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Hours Added'),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Date'),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_maintenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='completion_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Completion Remarks'),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='completion_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Completion Report'),
        ),
        migrations.AddField(
            model_name='componentmaintenance',
            name='maintenance_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Maintenance Status'),
        ),
    ]
