# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('flight_booking_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Flight Number')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('return_departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Return Departure Time')),
                ('return_arrival_time', models.DateTimeField(blank=True, null=True, verbose_name=' Return Arrival Time')),
                ('trip_type', models.CharField(choices=[('', '---------'), ('one-way', 'One Way'), ('round-trip', 'Round Trip'), ('multicity', 'Multi City')], default='one-way', max_length=20, verbose_name='Trip Type')),
                ('flight_tracking_id', models.CharField(max_length=100, verbose_name='Flight Booking Reference')),
                ('flight_booking_status', models.CharField(choices=[('', '----------------'), ('requested', 'Requested'), ('rejected', 'EAW Rejected'), ('cancelled', 'Customer Cancelled'), ('confirmed', 'Confirmed')], verbose_name='Booking Status')),
                ('booking_pax', models.PositiveSmallIntegerField(verbose_name='Booking Pax')),
                ('airway_distance', models.FloatField(blank=True, null=True)),
                ('airway_distance_true', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Airway Distance')),
                ('fuel', models.JSONField()),
                ('time', models.JSONField()),
                ('route', models.JSONField(default=list, verbose_name='Route')),
                ('update_comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Update Comments')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Recorded')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
                ('updated_by', models.CharField(blank=True, max_length=50, verbose_name='Updated By')),
                ('validity_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Valid')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
        ),
    ]
