# Generated by Django 5.0.2 on 2024-02-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_booking', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.aircraft', verbose_name='Aircraft'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_final_destination', to='maintenance.airport'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_origin', to='maintenance.airport'),
        ),
    ]
